import { Ionicons } from "@expo/vector-icons";
import { Animated, Pressable, StyleSheet, Text, View } from "react-native";
import { useEffect, useRef } from "react";
import { Colors } from "@/constants/Colors";
export const ScreenTitle=({children,subtitle}:{children:string;subtitle?:string})=><View><Text style={s.title}>{children}</Text>{subtitle?<Text style={s.subtitle}>{subtitle}</Text>:null}</View>;
export const ErrorState=({message,onRetry}:{message:string;onRetry:()=>void})=><View style={s.state}><View style={s.circle}><Ionicons name="cloud-offline-outline" size={28} color={Colors.primary}/></View><Text style={s.stateTitle}>Couldn't load this</Text><Text style={s.stateText}>{message}</Text><Pressable onPress={onRetry} style={s.retry}><Text style={s.retryText}>Try again</Text></Pressable></View>;
export const Skeleton=()=>{const x=useRef(new Animated.Value(-120)).current;useEffect(()=>{const loop=Animated.loop(Animated.timing(x,{toValue:420,duration:1150,useNativeDriver:true}));loop.start();return()=>loop.stop()},[x]);return <View>{[1,2,3,4].map(i=><View key={i} style={s.skeleton}><Animated.View style={[s.shimmer,{transform:[{translateX:x}]}]}/><View style={[s.skeletonLine,{width:i===1?"58%":"42%"}]}/><View style={[s.skeletonLine,s.short]}/></View>)}</View>};
const s=StyleSheet.create({title:{fontFamily:"Inter_700Bold",fontSize:22,color:Colors.text},subtitle:{fontFamily:"Inter_400Regular",fontSize:13,color:Colors.textTertiary,marginTop:4},state:{alignItems:"center",padding:42,marginTop:40},circle:{width:64,height:64,borderRadius:32,backgroundColor:Colors.primaryLight,alignItems:"center",justifyContent:"center",marginBottom:16},stateTitle:{fontFamily:"Inter_700Bold",fontSize:17,color:Colors.text},stateText:{fontFamily:"Inter_400Regular",fontSize:13,color:Colors.textSecondary,textAlign:"center",marginTop:6,lineHeight:19},retry:{backgroundColor:Colors.primary,borderRadius:12,paddingHorizontal:22,paddingVertical:11,marginTop:18},retryText:{fontFamily:"Inter_600SemiBold",color:"#fff"},skeleton:{height:68,borderRadius:14,backgroundColor:"#E7E9EF",marginBottom:10,overflow:"hidden",padding:15},shimmer:{position:"absolute",top:0,bottom:0,width:95,backgroundColor:"rgba(255,255,255,0.48)",transform:[{skewX:"-18deg"}]},skeletonLine:{height:10,borderRadius:5,backgroundColor:"#D8DBE4",marginBottom:9},short:{width:"30%",height:8,marginBottom:0}});

